#!/bin/sh
uci -q get wireless.radio0 > /dev/null || exit 0

# create an isolated network for wireless ygg links
uci -q batch << EOF
set network.piratemodem=interface
set network.piratemodem.proto='static'
set network.piratemodem.ipaddr='192.168.177.1'
set network.piratemodem.netmask='255.255.255.0'
EOF

# create dhcp for a network
uci -q batch << EOF
set dhcp.piratemodem=dhcp
set dhcp.piratemodem.start='100'
set dhcp.piratemodem.leasetime='12h'
set dhcp.piratemodem.limit='150'
set dhcp.piratemodem.interface='piratemodem'
EOF

# setup wifi ap
uci -q batch << EOF
set wireless.radio0.disabled='0'
set wireless.default_radio0.device='radio0'
set wireless.default_radio0.mode='ap'
set wireless.default_radio0.encryption='none'
set wireless.default_radio0.ssid='PirateModem'
set wireless.default_radio0.network='piratemodem'
EOF
